### PR TITLE
Fix POST encoding for data 

### PR DESCRIPTION
**Pull request by sberthelot**
no need for custom function, simply use urllib, otherwise it doesn't work for slashes or equal signs

### CODE REVIEW

**Comment by Reamer** [comment]
Thanks for your PR. What is your opinion for using this library (http://docs.python-requests.org/en/latest/index.html)?

**Comment by sberthelot** [comment]
Sorry I never tried it so I can't say. But looking at my current Ubuntu 16.04 (LTS) production servers it doesn't seem to be installed by default (maybe available in a package or repo).
I usually prefer to stick on base packages for this kind of use...

**Comment by Reamer** [comment]
I agree with you. On CentOS 6.9, the "request" library is also not available by default. Hopefully I have some time tomorrow for testing your changes.

**Review by Reamer — APPROVED** [review]

**Comment by Reamer** [comment]
Merged with https://github.com/Reamer/icinga2-mattermost/commit/9ac4159437669e3021e3ad3cd7443241c3633c89

**Pull request closed without merging**
